version: '3.8'

services:
  api:
    build: ./api
    container_name: eduon_api
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    depends_on:
      - db

  db:
    image: supabase/postgres:15.1.0.81
    container_name: eduon_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  studio:
    image: supabase/studio:latest
    container_name: eduon_studio
    restart: always
    ports:
      - "5050:3000"
    environment:
      SUPABASE_URL: http://kong:8000
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
    depends_on:
      - db
      - kong

  kong:
    image: supabase/kong:latest
    container_name: eduon_kong
    restart: always
    ports:
      - "8000:8000"
      - "8443:8443"
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
    volumes:
      - ./supabase/kong.yml:/var/lib/kong/kong.yml

volumes:
  db_data:
